services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
        
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
      - adminer-data:/var/www/adminer

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    env_file: .env

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - adminer-data:/var/www/adminer

volumes:
  wordpress-data:
  mariadb-data:
  adminer-data:

networks:
  inception:
