#!/bin/bash

echo -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';\nCREATE DATABASE $MYSQL_DATABASE;\nCREATE USER $MYSQL_USER@'%' IDENTIFIED BY '$MYSQL_PASSWORD';\nGRANT ALL ON $MYSQL_DATABASE.* TO $MYSQL_USER@'%';\n" > init.sql;

exec "$@"
